-- ============================================================
-- Sales Performance by Country and Device
-- ============================================================
-- Business question:
-- Which countries and devices generate the most revenue?
-- ============================================================

WITH sales_by_country_device AS (

  SELECT
    sp.country,
    sp.device,

    -- Number of unique sessions with a purchase.
    COUNT(DISTINCT o.ga_session_id) AS purchase_sessions,

    -- Total revenue generated by purchased products.
    SUM(p.price) AS revenue

  FROM `data-analytics-mate.DA.order` AS o

  JOIN `data-analytics-mate.DA.product` AS p
    ON o.item_id = p.item_id

  JOIN `data-analytics-mate.DA.session_params` AS sp
    ON o.ga_session_id = sp.ga_session_id

  GROUP BY
    sp.country,
    sp.device
),

sales_metrics AS (

  SELECT
    country,
    device,
    purchase_sessions,
    revenue,

    -- Average revenue per purchase session.
    SAFE_DIVIDE(
      revenue,
      purchase_sessions
    ) AS avg_revenue_per_purchase_session,

    -- Percentage of total revenue.
    SAFE_DIVIDE(
      revenue,
      SUM(revenue) OVER ()
    ) * 100 AS revenue_share,

    -- Revenue ranking.
    RANK() OVER (
      ORDER BY revenue DESC
    ) AS revenue_rank

  FROM sales_by_country_device
)

SELECT
  country,
  device,
  purchase_sessions,

  ROUND(revenue, 2) AS revenue,

  ROUND(
    avg_revenue_per_purchase_session,
    2
  ) AS avg_revenue_per_purchase_session,

  ROUND(
    revenue_share,
    2
  ) AS revenue_share,

  revenue_rank

FROM sales_metrics

ORDER BY
  revenue_rank;
